onboarding = false

[keys]
prefix = "ctrl+s"
detach = "prefix+d"
split_vertical = "prefix+%"
split_horizontal = "prefix+\""

[ui]
prompt_new_tab_name = false

[[keys.command]]
key = "prefix+s"
type = "popup"
command = '''
herdr workspace list |
  jq -r '.result.workspaces[] | select(.focused | not) | "\(.workspace_id)\t\(.label)"' |
  fzf --reverse --with-nth 2 |
  cut -f 1 |
  xargs herdr workspace focus > /dev/null
'''
description = "switch workspace"
