tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"

brew "cloud-sql-proxy"
brew "composer"
brew "jq"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "neofetch"
brew "tmux"

cask "1password"
cask "alfred"
cask "alt-tab"
cask "android-studio"
cask "appcleaner"
cask "bartender"
cask "deepl"
cask "docker"
cask "dropbox"
cask "flutter"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "iterm2"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "logi-options-plus"
cask "monitorcontrol"
cask "popclip"
cask "rectangle"
cask "slack"
cask "utm"
cask "vagrant"
cask "vagrant-vmware-utility"
cask "visual-studio-code"
cask "vmware-fusion"
cask "zoom"

mas "Amphetamine", id: 937984704
mas "Xcode", id: 497799835

vscode "asvetliakov.vscode-neovim"
vscode "github.copilot"
vscode "golang.go"
vscode "iamhyc.overleaf-workshop"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-python.black-formatter"
vscode "ms-python.flake8"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vsliveshare.vsliveshare"
vscode "usernamehw.errorlens"
