tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"

brew "act"
brew "cloud-sql-proxy"
brew "composer"
brew "jq"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "marp-cli"
brew "neofetch"
brew "tmux"

cask "google-cloud-sdk"
cask "vagrant"
