mode: session
nerdfont: false
window_prefix: ""
worktree_dir: "../"
worktree_prefix: "{project}="

windows:
  - panes:
      - command: nvim
  - panes:
      - command: opencode
  - panes:
      - focus: true
