[worktree]
basedir = "~/ghq"
auto_mkdir = true

[finder]
preview = true

[naming]
template = '{{.Host}}/{{.Owner}}/{{.Repository}}={{.Branch}}'
sanitize_chars = { "/" = "-", ":" = "-" }

[cd]
launch_shell = false

[ui]
icons = true
tilde_home = true
