name: CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./install.sh

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./install.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_BUNDLE_MAS_SKIP: "Amphetamine Kindle WireGuard Xcode"
