[tools]
act = "latest"
ansible = { version = "latest", expose = ["ansible-core"] }
aws-cli = "latest"
bat = "latest"
bottom = "latest"
buf = "latest"
claude = "latest"
cloud-sql-proxy = "latest"
cocoapods = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
gemini-cli = "latest"
ghq = "latest"
git-lfs = "latest"
github-cli = "latest"
go = "latest"
herdr = "latest"
hunk = "latest"
jq = "latest"
kustomize = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
pipx = "latest"
poetry = "latest"
python = "3.13"
ripgrep = "latest"
ruby = "3.3"
rust = "latest"
terraform = "latest"
terragrunt = "latest"
tlrc = "latest"
tokei = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
yarn = "latest"
yq = "latest"
zoxide = "latest"
"cargo:https://github.com/nakatuba/workmux" = "latest"
"go:github.com/cweill/gotests/gotests" = "latest"
"npm:@googleworkspace/cli" = "latest"
"pipx:argcomplete" = "latest"
"pipx:git+https://github.com/nakatuba/pgcli.git" = { version = "latest", with = ["psycopg_binary"] }
"pipx:markitdown" = { version = "latest", extras = "all" }
"pipx:mycli" = "latest"
"pipx:neovim-remote" = "latest"
"pipx:powerline-status" = "latest"
"pipx:trash-cli" = "latest"

[settings]
trusted_config_paths = ["~/dotfiles", "~/ghq"]
